name: CI/CD

on:
  pull_request:
    branches:
      - dev
      - qa
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: prusciplus-app
        run: npm install

      - name: Run tests
        working-directory: prusciplus-app
        run: npm run test