name: Build and Publish Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/ofesquiro/prusciplus-frontend/app:${{ github.ref_name }} .
        
      - name: Test the Docker image
        run: |
          docker run -d -p 80:80 --name test-container ghcr.io/ofesquiro/prusciplus-frontend/app:${{ github.ref_name }}
          sleep 10
          docker ps -a
          docker logs test-container
          docker rm -f test-container
      
      - name: Push the Docker image
        run: |
          docker push ghcr.io/ofesquiro/prusciplus-frontend/app:${{ github.ref_name }}